<?php
/**
 * Bunny Learning — configuration template.
 * install.php generates config.php from this. Do not edit this file directly
 * on a production server; edit config.php instead (it is never committed).
 */
return [
    // --- MySQL database ---
    'db_host'    => 'localhost',
    'db_name'    => 'bunny_learning',
    'db_user'    => 'bunny_user',
    'db_pass'    => 'CHANGE_ME',
    'db_charset' => 'utf8mb4',

    // --- SMTP mail server ---
    'smtp_host'      => 'smtp.example.com',
    'smtp_port'      => 587,
    'smtp_secure'    => 'tls',        // none | tls (STARTTLS) | ssl
    'smtp_user'      => '',
    'smtp_pass'      => '',
    'smtp_from'      => 'noreply@example.com',
    'smtp_from_name' => 'Bunny Learning',

    // --- App ---
    'app_url'    => 'https://example.com',   // public base URL, used in email links
    'app_name'   => 'Bunny Learning',
];
